name: Build Windows and Mac Apps

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build Windows Executable
        if: matrix.os == 'windows-latest'
        run: npm run build-exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Mac DMG
        if: matrix.os == 'macos-latest'
        run: npm run build-mac
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: allys-oddone-builds-${{ matrix.os }}
          path: |
            dist/*.exe
            dist/*.dmg
